INSERT INTO COUNTRY (NAME, COUNTRYCODE, CAPITAL, CURRENCY, CALLINGCODE, POPULATION, LIFEEXPECTANCY, SURFACEAREA, FORESTEDAREA, GDP, REGION, FLAG) VALUES
    ('Afghanistan', 'AF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/AF.png'),
    ('Albania', 'AL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/AL.png'),
    ('Algeria', 'DZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/DZ.png'),
    ('American Samoa', 'AS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/AS.png'),
    ('Andorra', 'AD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/AD.png'),
    ('Angola', 'AO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/AO.png'),
    ('Anguilla', 'AI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/AI.png'),
    ('Antarctica', 'AQ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/AQ.png'),
    ('Antigua and Barbuda', 'AG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/AG.png'),
    ('Argentina', 'AR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/AR.png'),
    ('Armenia', 'AM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/AM.png'),
    ('Aruba', 'AW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/AW.png'),
    ('Australia', 'AU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/AU.png'),
    ('Austria', 'AT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/AT.png'),
    ('Azerbaijan', 'AZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/AZ.png'),
    ('Bahamas', 'BS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/BS.png'),
    ('Bahrain', 'BH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/BH.png'),
    ('Bangladesh', 'BD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/BD.png'),
    ('Barbados', 'BB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/BB.png'),
    ('Belarus', 'BY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/BY.png'),
    ('Belgium', 'BE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/BE.png'),
    ('Belize', 'BZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/BZ.png'),
    ('Benin', 'BJ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/BJ.png'),
    ('Bermuda', 'BM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/BM.png'),
    ('Bhutan', 'BT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/BT.png'),
    ('Bosnia and Herzegovina', 'BA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/BA.png'),
    ('Botswana', 'BW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/BW.png'),
    ('Bouvet Island', 'BV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/BV.png'),
    ('Brazil', 'BR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/BR.png'),
    ('British Indian Ocean Territory', 'IO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/IO.png'),
    ('Brunei Darussalam', 'BN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/BN.png'),
    ('Bulgaria', 'BG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/BG.png'),
    ('Burkina Faso', 'BF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/BF.png'),
    ('Burundi', 'BI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/BI.png'),
    ('Cambodia', 'KH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/KH.png'),
    ('Cameroon', 'CM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/CM.png'),
    ('Canada', 'CA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/CA.png'),
    ('Cape Verde', 'CV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/CV.png'),
    ('Cayman Islands', 'KY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/KY.png'),
    ('Central African Republic', 'CF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/CF.png'),
    ('Chad', 'TD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/TD.png'),
    ('Chile', 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/CL.png'),
    ('China', 'CN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/CN.png'),
    ('Christmas Island', 'CX', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/CX.png'),
    ('Cocos (Keeling) Islands', 'CC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/CC.png'),
    ('Colombia', 'CO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/CO.png'),
    ('Comoros', 'KM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/KM.png'),
    ('Congo', 'CG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/CG.png'),
    ('Cook Islands', 'CK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/CK.png'),
    ('Costa Rica', 'CR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/CR.png'),
    ('Croatia', 'HR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/HR.png'),
    ('Cuba', 'CU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/CU.png'),
    ('Cyprus', 'CY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/CY.png'),
    ('Czech Republic', 'CZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/CZ.png'),
    ('Denmark', 'DK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/DK.png'),
    ('Djibouti', 'DJ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/DJ.png'),
    ('Dominica', 'DM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/DM.png'),
    ('Dominican Republic', 'DO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/DO.png'),
    ('Ecuador', 'EC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/EC.png'),
    ('Egypt', 'EG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/EG.png'),
    ('El Salvador', 'SV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/SV.png'),
    ('Equatorial Guinea', 'GQ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/GQ.png'),
    ('Eritrea', 'ER', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ER.png'),
    ('Estonia', 'EE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/EE.png'),
    ('Ethiopia', 'ET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ET.png'),
    ('Falkland Islands (Malvinas)' ,'FK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/FK.png'),
    ('Faroe Islands', 'FO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/FO.png'),
    ('Fiji', 'FJ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/FJ.png'),
    ('Finland', 'FI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/FI.png'),
    ('France', 'FR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/FR.png'),
    ('French Guiana', 'GF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/GF.png'),
    ('French Polynesia', 'PF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/PF.png'),
    ('French Southern Territories', 'TF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/TF.png'),
    ('Gabon', 'GA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/GA.png'),
    ('Gambia', 'GM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/GM.png'),
    ('Georgia', 'GE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/GE.png'),
    ('Germany', 'DE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/DE.png'),
    ('Ghana', 'GH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/GH.png'),
    ('Gibraltar', 'GI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/GI.png'),
    ('Greece', 'GR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/GR.png'),
    ('Greenland', 'GL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/GL.png'),
    ('Grenada', 'GD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/GD.png'),
    ('Guadeloupe', 'GP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/GP.png'),
    ('Guam', 'GU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/GU.png'),
    ('Guatemala', 'GT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/GT.png'),
    ('Guernsey', 'GG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/GG.png'),
    ('Guinea', 'GN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/GN.png'),
    ('Guinea-Bissau', 'GW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/GW.png'),
    ('Guyana', 'GY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/GY.png'),
    ('Haiti', 'HT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/HT.png'),
    ('Heard Island and McDonald Islands', 'HM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/HM.png'),
    ('Holy See (Vatican City State)' ,'VA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/VA.png'),
    ('Honduras', 'HN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/HN.png'),
    ('Hong Kong', 'HK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/HK.png'),
    ('Hungary', 'HU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/HU.png'),
    ('Iceland', 'IS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/IS.png'),
    ('India', 'IN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/IN.png'),
    ('Indonesia', 'ID', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ID.png'),
    ('Iraq', 'IQ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/IQ.png'),
    ('Ireland', 'IE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/IE.png'),
    ('Isle of Man', 'IM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/IM.png'),
    ('Israel', 'IL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/IL.png'),
    ('Italy', 'IT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/IT.png'),
    ('Jamaica', 'JM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/JM.png'),
    ('Japan', 'JP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/JP.png'),
    ('Jersey', 'JE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/JE.png'),
    ('Jordan', 'JO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/JO.png'),
    ('Kazakhstan', 'KZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/KZ.png'),
    ('Kenya', 'KE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/KE.png'),
    ('Kiribati', 'KI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/KI.png'),
    ('Kuwait', 'KW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/KW.png'),
    ('Kyrgyzstan', 'KG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/KG.png'),
    ('Lao Peoples Democratic Republic', 'LA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/LA.png'),
    ('Latvia', 'LV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/LV.png'),
    ('Lebanon', 'LB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/LB.png'),
    ('Lesotho', 'LS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/LS.png'),
    ('Liberia', 'LR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/LR.png'),
    ('Libya', 'LY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/LY.png'),
    ('Liechtenstein', 'LI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/LI.png'),
    ('Lithuania', 'LT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/LT.png'),
    ('Luxembourg', 'LU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/LU.png'),
    ('Macao', 'MO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/MO.png'),
    ('Madagascar', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/MG.png'),
    ('Malawi', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/MW.png'),
    ('Malaysia', 'MY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/MY.png'),
    ('Maldives', 'MV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/MV.png'),
    ('Mali', 'ML', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ML.png'),
    ('Malta', 'MT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/MT.png'),
    ('Marshall Islands', 'MH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/MH.png'),
    ('Martinique', 'MQ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/MQ.png'),
    ('Mauritania', 'MR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/MR.png'),
    ('Mauritius', 'MU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/MU.png'),
    ('Mayotte', 'YT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/YT.png'),
    ('Mexico', 'MX', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/MX.png'),
    ('Monaco', 'MC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/MC.png'),
    ('Mongolia', 'MN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/MN.png'),
    ('Montenegro', 'ME', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ME.png'),
    ('Montserrat', 'MS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/MS.png'),
    ('Morocco', 'MA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/MA.png'),
    ('Mozambique', 'MZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/MZ.png'),
    ('Myanmar', 'MM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/MM.png'),
    ('Namibia', 'NA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/NA.png'),
    ('Nauru', 'NR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/NR.png'),
    ('Nepal', 'NP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/NP.png'),
    ('Netherlands', 'NL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/NL.png'),
    ('New Caledonia', 'NC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/NC.png'),
    ('New Zealand', 'NZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/NZ.png'),
    ('Nicaragua', 'NI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/NI.png'),
    ('Niger', 'NE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/NE.png'),
    ('Nigeria', 'NG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/NG.png'),
    ('Niue', 'NU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/NU.png'),
    ('Norfolk Island', 'NF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/NF.png'),
    ('Northern Mariana Islands', 'MP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/MP.png'),
    ('Norway', 'NO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/NO.png'),
    ('Oman', 'OM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/OM.png'),
    ('Pakistan', 'PK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/PK.png'),
    ('Palau', 'PW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/PW.png'),
    ('Panama', 'PA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/PA.png'),
    ('Papua New Guinea', 'PG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/PG.png'),
    ('Paraguay', 'PY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/PY.png'),
    ('Peru', 'PE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/PE.png'),
    ('Philippines', 'PH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/PH.png'),
    ('Pitcairn', 'PN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/PN.png'),
    ('Poland', 'PL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/PL.png'),
    ('Portugal', 'PT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/PT.png'),
    ('Puerto Rico', 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/PR.png'),
    ('Qatar', 'QA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/QA.png'),
    ('Romania', 'RO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/RO.png'),
    ('Russian Federation', 'RU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/RU.png'),
    ('Rwanda', 'RW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/RW.png'),
    ('Saint Kitts and Nevis', 'KN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/KN.png'),
    ('Saint Lucia', 'LC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/LC.png'),
    ('Saint Martin (French part)' ,'MF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/MF.png'),
    ('Saint Pierre and Miquelon', 'PM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/PM.png'),
    ('Saint Vincent and the Grenadines', 'VC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/VC.png'),
    ('Samoa', 'WS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/WS.png'),
    ('San Marino', 'SM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/SM.png'),
    ('Sao Tome and Principe', 'ST', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ST.png'),
    ('Saudi Arabia', 'SA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/SA.png'),
    ('Senegal', 'SN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/SN.png'),
    ('Serbia', 'RS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/RS.png'),
    ('Seychelles', 'SC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/SC.png'),
    ('Sierra Leone', 'SL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/SL.png'),
    ('Singapore', 'SG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/SG.png'),
    ('Sint Maarten (Dutch part)' ,'SX', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/SX.png'),
    ('Slovakia', 'SK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/SK.png'),
    ('Slovenia', 'SI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/SI.png'),
    ('Solomon Islands', 'SB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/SB.png'),
    ('Somalia', 'SO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/SO.png'),
    ('South Africa', 'ZA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ZA.png'),
    ('South Georgia and the South Sandwich Islands', 'GS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/GS.png'),
    ('South Sudan', 'SS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/SS.png'),
    ('Spain', 'ES', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ES.png'),
    ('Sri Lanka', 'LK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/LK.png'),
    ('Sudan', 'SD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/SD.png'),
    ('Suriname', 'SR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/SR.png'),
    ('Svalbard and Jan Mayen', 'SJ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/SJ.png'),
    ('Swaziland', 'SZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/SZ.png'),
    ('Sweden', 'SE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/SE.png'),
    ('Switzerland', 'CH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/CH.png'),
    ('Syrian Arab Republic', 'SY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/SY.png'),
    ('Tajikistan', 'TJ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/TJ.png'),
    ('Thailand', 'TH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/TH.png'),
    ('Timor-Leste', 'TL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/TL.png'),
    ('Togo', 'TG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/TG.png'),
    ('Tokelau', 'TK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/TK.png'),
    ('Tonga', 'TO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/TO.png'),
    ('Trinidad and Tobago', 'TT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/TT.png'),
    ('Tunisia', 'TN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/TN.png'),
    ('Turkey', 'TR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/TR.png'),
    ('Turkmenistan', 'TM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/TM.png'),
    ('Turks and Caicos Islands', 'TC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/TC.png'),
    ('Tuvalu', 'TV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/TV.png'),
    ('Uganda', 'UG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/UG.png'),
    ('Ukraine', 'UA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/UA.png'),
    ('United Arab Emirates', 'AE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/AE.png'),
    ('United Kingdom', 'GB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/GB.png'),
    ('United States', 'US', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/US.png'),
    ('United States Minor Outlying Islands', 'UM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/UM.png'),
    ('Uruguay', 'UY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/UY.png'),
    ('Uzbekistan', 'UZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/UZ.png'),
    ('Vanuatu', 'VU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/VU.png'),
    ('Viet Nam', 'VN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/VN.png'),
    ('Wallis and Futuna', 'WF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/WF.png'),
    ('Western Sahara', 'EH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/EH.png'),
    ('Yemen', 'YE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/YE.png'),
    ('Zambia', 'ZM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ZM.png'),
    ('Zimbabwe', 'ZW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ZW.png'),
