INSERT INTO COUNTRY (NAME, COUNTRYCODE, CAPITAL, CURRENCY, CALLINGCODE, POPULATION, LIFEEXPECTANCY, SURFACEAREA, FORESTEDAREA, GDP, REGION, FLAG) VALUES
    ('Afghanistan', 'AF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/af.png'),
    ('Albania', 'AL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/al.png'),
    ('Algeria', 'DZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/dz.png'),
    ('American Samoa', 'AS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/as.png'),
    ('Andorra', 'AD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ad.png'),
    ('Angola', 'AO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ao.png'),
    ('Anguilla', 'AI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ai.png'),
    ('Antarctica', 'AQ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/aq.png'),
    ('Antigua and Barbuda', 'AG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ag.png'),
    ('Argentina', 'AR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ar.png'),
    ('Armenia', 'AM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/am.png'),
    ('Aruba', 'AW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/aw.png'),
    ('Australia', 'AU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/au.png'),
    ('Austria', 'AT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/at.png'),
    ('Azerbaijan', 'AZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/az.png'),
    ('Bahamas', 'BS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/bs.png'),
    ('Bahrain', 'BH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/bh.png'),
    ('Bangladesh', 'BD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/bd.png'),
    ('Barbados', 'BB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/bb.png'),
    ('Belarus', 'BY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/by.png'),
    ('Belgium', 'BE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/be.png'),
    ('Belize', 'BZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/bz.png'),
    ('Benin', 'BJ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/bj.png'),
    ('Bermuda', 'BM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/bm.png'),
    ('Bhutan', 'BT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/bt.png'),
    ('Bosnia and Herzegovina', 'BA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ba.png'),
    ('Botswana', 'BW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/bw.png'),
    ('Bouvet Island', 'BV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/bv.png'),
    ('Brazil', 'BR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/br.png'),
    ('British Indian Ocean Territory', 'IO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/io.png'),
    ('Brunei Darussalam', 'BN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/bn.png'),
    ('Bulgaria', 'BG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/bg.png'),
    ('Burkina Faso', 'BF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/bf.png'),
    ('Burundi', 'BI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/bi.png'),
    ('Cambodia', 'KH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/kh.png'),
    ('Cameroon', 'CM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/cm.png'),
    ('Canada', 'CA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ca.png'),
    ('Cape Verde', 'CV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/cv.png'),
    ('Cayman Islands', 'KY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ky.png'),
    ('Central African Republic', 'CF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/cf.png'),
    ('Chad', 'TD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/td.png'),
    ('Chile', 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/cl.png'),
    ('China', 'CN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/cn.png'),
    ('Christmas Island', 'CX', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/cx.png'),
    ('Cocos (Keeling) Islands', 'CC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/cc.png'),
    ('Colombia', 'CO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/co.png'),
    ('Comoros', 'KM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/km.png'),
    ('Congo', 'CG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/cg.png'),
    ('Cook Islands', 'CK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ck.png'),
    ('Costa Rica', 'CR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/cr.png'),
    ('Croatia', 'HR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/hr.png'),
    ('Cuba', 'CU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/cu.png'),
    ('Cyprus', 'CY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/cy.png'),
    ('Czech Republic', 'CZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/cz.png'),
    ('Denmark', 'DK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/dk.png'),
    ('Djibouti', 'DJ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/dj.png'),
    ('Dominica', 'DM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/dm.png'),
    ('Dominican Republic', 'DO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/do.png'),
    ('Ecuador', 'EC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ec.png'),
    ('Egypt', 'EG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/eg.png'),
    ('El Salvador', 'SV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/sv.png'),
    ('Equatorial Guinea', 'GQ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/gq.png'),
    ('Eritrea', 'ER', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/er.png'),
    ('Estonia', 'EE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ee.png'),
    ('Ethiopia', 'ET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/et.png'),
    ('Falkland Islands (Malvinas)' ,'FK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/fk.png'),
    ('Faroe Islands', 'FO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/fo.png'),
    ('Fiji', 'FJ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/fj.png'),
    ('Finland', 'FI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/fi.png'),
    ('France', 'FR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/fr.png'),
    ('French Guiana', 'GF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/gf.png'),
    ('French Polynesia', 'PF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/pf.png'),
    ('French Southern Territories', 'TF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/tf.png'),
    ('Gabon', 'GA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ga.png'),
    ('Gambia', 'GM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/gm.png'),
    ('Georgia', 'GE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ge.png'),
    ('Germany', 'DE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/de.png'),
    ('Ghana', 'GH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/gh.png'),
    ('Gibraltar', 'GI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/gi.png'),
    ('Greece', 'GR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/gr.png'),
    ('Greenland', 'GL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/gl.png'),
    ('Grenada', 'GD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/gd.png'),
    ('Guadeloupe', 'GP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/gp.png'),
    ('Guam', 'GU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/gu.png'),
    ('Guatemala', 'GT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/gt.png'),
    ('Guernsey', 'GG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/gg.png'),
    ('Guinea', 'GN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/gn.png'),
    ('Guinea-Bissau', 'GW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/gw.png'),
    ('Guyana', 'GY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/gy.png'),
    ('Haiti', 'HT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ht.png'),
    ('Heard Island and McDonald Islands', 'HM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/hm.png'),
    ('Holy See (Vatican City State)' ,'VA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/va.png'),
    ('Honduras', 'HN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/hn.png'),
    ('Hong Kong', 'HK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/hk.png'),
    ('Hungary', 'HU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/hu.png'),
    ('Iceland', 'IS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/is.png'),
    ('India', 'IN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/in.png'),
    ('Indonesia', 'ID', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/id.png'),
    ('Iraq', 'IQ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/iq.png'),
    ('Ireland', 'IE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ie.png'),
    ('Isle of Man', 'IM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/im.png'),
    ('Israel', 'IL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/il.png'),
    ('Italy', 'IT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/it.png'),
    ('Jamaica', 'JM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/jm.png'),
    ('Japan', 'JP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/jp.png'),
    ('Jersey', 'JE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/je.png'),
    ('Jordan', 'JO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/jo.png'),
    ('Kazakhstan', 'KZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/kz.png'),
    ('Kenya', 'KE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ke.png'),
    ('Kiribati', 'KI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ki.png'),
    ('Kuwait', 'KW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/kw.png'),
    ('Kyrgyzstan', 'KG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/kg.png'),
    ('Lao Peoples Democratic Republic', 'LA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/la.png'),
    ('Latvia', 'LV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/lv.png'),
    ('Lebanon', 'LB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/lb.png'),
    ('Lesotho', 'LS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ls.png'),
    ('Liberia', 'LR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/lr.png'),
    ('Libya', 'LY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ly.png'),
    ('Liechtenstein', 'LI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/li.png'),
    ('Lithuania', 'LT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/lt.png'),
    ('Luxembourg', 'LU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/lu.png'),
    ('Macao', 'MO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/mo.png'),
    ('Madagascar', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/mg.png'),
    ('Malawi', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/mw.png'),
    ('Malaysia', 'MY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/my.png'),
    ('Maldives', 'MV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/mv.png'),
    ('Mali', 'ML', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ml.png'),
    ('Malta', 'MT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/mt.png'),
    ('Marshall Islands', 'MH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/mh.png'),
    ('Martinique', 'MQ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/mq.png'),
    ('Mauritania', 'MR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/mr.png'),
    ('Mauritius', 'MU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/mu.png'),
    ('Mayotte', 'YT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/yt.png'),
    ('Mexico', 'MX', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/mx.png'),
    ('Monaco', 'MC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/mc.png'),
    ('Mongolia', 'MN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/mn.png'),
    ('Montenegro', 'ME', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/me.png'),
    ('Montserrat', 'MS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ms.png'),
    ('Morocco', 'MA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ma.png'),
    ('Mozambique', 'MZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/mz.png'),
    ('Myanmar', 'MM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/mm.png'),
    ('Namibia', 'NA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/na.png'),
    ('Nauru', 'NR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/nr.png'),
    ('Nepal', 'NP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/np.png'),
    ('Netherlands', 'NL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/nl.png'),
    ('New Caledonia', 'NC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/nc.png'),
    ('New Zealand', 'NZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/nz.png'),
    ('Nicaragua', 'NI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ni.png'),
    ('Niger', 'NE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ne.png'),
    ('Nigeria', 'NG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ng.png'),
    ('Niue', 'NU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/nu.png'),
    ('Norfolk Island', 'NF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/nf.png'),
    ('Northern Mariana Islands', 'MP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/mp.png'),
    ('Norway', 'NO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/no.png'),
    ('Oman', 'OM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/om.png'),
    ('Pakistan', 'PK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/pk.png'),
    ('Palau', 'PW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/pw.png'),
    ('Panama', 'PA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/pa.png'),
    ('Papua New Guinea', 'PG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/pg.png'),
    ('Paraguay', 'PY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/py.png'),
    ('Peru', 'PE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/pe.png'),
    ('Philippines', 'PH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ph.png'),
    ('Pitcairn', 'PN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/pn.png'),
    ('Poland', 'PL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/pl.png'),
    ('Portugal', 'PT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/pt.png'),
    ('Puerto Rico', 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/pr.png'),
    ('Qatar', 'QA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/qa.png'),
    ('Romania', 'RO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ro.png'),
    ('Russian Federation', 'RU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ru.png'),
    ('Rwanda', 'RW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/rw.png'),
    ('Saint Kitts and Nevis', 'KN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/kn.png'),
    ('Saint Lucia', 'LC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/lc.png'),
    ('Saint Martin (French part)' ,'MF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/mf.png'),
    ('Saint Pierre and Miquelon', 'PM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/pm.png'),
    ('Saint Vincent and the Grenadines', 'VC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/vc.png'),
    ('Samoa', 'WS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ws.png'),
    ('San Marino', 'SM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/sm.png'),
    ('Sao Tome and Principe', 'ST', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/st.png'),
    ('Saudi Arabia', 'SA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/sa.png'),
    ('Senegal', 'SN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/sn.png'),
    ('Serbia', 'RS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/rs.png'),
    ('Seychelles', 'SC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/sc.png'),
    ('Sierra Leone', 'SL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/sl.png'),
    ('Singapore', 'SG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/sg.png'),
    ('Sint Maarten (Dutch part)' ,'SX', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/sx.png'),
    ('Slovakia', 'SK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/sk.png'),
    ('Slovenia', 'SI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/si.png'),
    ('Solomon Islands', 'SB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/sb.png'),
    ('Somalia', 'SO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/so.png'),
    ('South Africa', 'ZA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/za.png'),
    ('South Georgia and the South Sandwich Islands', 'GS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/gs.png'),
    ('South Sudan', 'SS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ss.png'),
    ('Spain', 'ES', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/es.png'),
    ('Sri Lanka', 'LK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/lk.png'),
    ('Sudan', 'SD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/sd.png'),
    ('Suriname', 'SR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/sr.png'),
    ('Svalbard and Jan Mayen', 'SJ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/sj.png'),
    ('Swaziland', 'SZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/sz.png'),
    ('Sweden', 'SE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/se.png'),
    ('Switzerland', 'CH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ch.png'),
    ('Syrian Arab Republic', 'SY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/sy.png'),
    ('Tajikistan', 'TJ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/tj.png'),
    ('Thailand', 'TH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/th.png'),
    ('Timor-Leste', 'TL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/tl.png'),
    ('Togo', 'TG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/tg.png'),
    ('Tokelau', 'TK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/tk.png'),
    ('Tonga', 'TO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/to.png'),
    ('Trinidad and Tobago', 'TT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/tt.png'),
    ('Tunisia', 'TN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/tn.png'),
    ('Turkey', 'TR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/tr.png'),
    ('Turkmenistan', 'TM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/tm.png'),
    ('Turks and Caicos Islands', 'TC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/tc.png'),
    ('Tuvalu', 'TV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/tv.png'),
    ('Uganda', 'UG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ug.png'),
    ('Ukraine', 'UA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ua.png'),
    ('United Arab Emirates', 'AE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ae.png'),
    ('United Kingdom', 'GB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/gb.png'),
    ('United States', 'US', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/us.png'),
    ('United States Minor Outlying Islands', 'UM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/um.png'),
    ('Uruguay', 'UY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/uy.png'),
    ('Uzbekistan', 'UZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/uz.png'),
    ('Vanuatu', 'VU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/vu.png'),
    ('Viet Nam', 'VN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/vn.png'),
    ('Wallis and Futuna', 'WF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/wf.png'),
    ('Western Sahara', 'EH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/eh.png'),
    ('Yemen', 'YE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/ye.png'),
    ('Zambia', 'ZM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/zm.png'),
    ('Zimbabwe', 'ZW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,'https://flagcdn.com/h240/zw.png'),
