INSERT INTO COUNTRY (NAME, COUNTRY_CODE, CAPITAL, CO2EMISSIONS, CURRENCY, EXPORTS, FORESTED_AREA, GDP, HOMICIDE_RATE, IMPORTS, INFANT_MORTALITY, INTERNET_USERS, LIFE_EXPECTANCY_FEMALE, LIFE_EXPECTANCY_MALE, POPULATION, POPULATION_DENSITY, POPULATION_GROWTH, SECONDARY_SCHOOL_ENROLLMENT_FEMALE, SECONDARY_SCHOOL_ENROLLMENT_MALE, SURFACE_AREA, UNEMPLOYMENT_RATE, FLAG, CONTINENT) VALUES
    ('Afghanistan', 'AF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/af.png', 'Asia'),
    ('Albania', 'AL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/al.png', 'Europe'),
    ('American Samoa', 'AS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/as.png', 'Oceania'),
    ('Andorra', 'AD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ad.png', 'Europe'),
    ('Angola', 'AO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ao.png', 'Africa'),
    ('Anguilla', 'AI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ai.png', 'Americas'),
    ('Antigua and Barbuda', 'AG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ag.png', 'Americas'),
    ('Argentina', 'AR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ar.png', 'Americas'),
    ('Armenia', 'AM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/am.png', 'Asia'),
    ('Aruba', 'AW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/aw.png', 'Americas'),
    ('Australia', 'AU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/au.png', 'Oceania'),
    ('Austria', 'AT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/at.png', 'Europe'),
    ('Azerbaijan', 'AZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/az.png', 'Asia'),
    ('Bahamas', 'BS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/bs.png', 'Americas'),
    ('Bahrain', 'BH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/bh.png', 'Asia'),
    ('Bangladesh', 'BD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/bd.png', 'Asia'),
    ('Barbados', 'BB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/bb.png', 'Americas'),
    ('Belarus', 'BY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/by.png', 'Europe'),
    ('Belgium', 'BE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/be.png', 'Europe'),
    ('Belize', 'BZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/bz.png', 'Americas'),
    ('Benin', 'BJ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/bj.png', 'Africa'),
    ('Bermuda', 'BM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/bm.png', 'Americas'),
    ('Bhutan', 'BT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/bt.png', 'Asia'),
    ('Bosnia and Herzegovina', 'BA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ba.png', 'Europe'),
    ('Botswana', 'BW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/bw.png', 'Africa'),
    ('Brazil', 'BR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/br.png', 'Americas'),
    ('Brunei Darussalam', 'BN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/bn.png', 'Asia'),
    ('Bulgaria', 'BG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/bg.png', 'Europe'),
    ('Burkina Faso', 'BF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/bf.png', 'Africa'),
    ('Burundi', 'BI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/bi.png', 'Africa'),
    ('Cambodia', 'KH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/kh.png', 'Asia'),
    ('Cameroon', 'CM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/cm.png', 'Africa'),
    ('Canada', 'CA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ca.png', 'Americas'),
    ('Cape Verde', 'CV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/cv.png', 'Africa'),
    ('Cayman Islands', 'KY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ky.png', 'Americas'),
    ('Central African Republic', 'CF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/cf.png', 'Africa'),
    ('Chad', 'TD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/td.png', 'Africa'),
    ('Chile', 'CL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/cl.png', 'Americas'),
    ('China', 'CN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/cn.png', 'Asia'),
    ('Colombia', 'CO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/co.png', 'Americas'),
    ('Comoros', 'KM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/km.png', 'Africa'),
    ('Congo', 'CG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/cg.png', 'Africa'),
    ('Cook Islands', 'CK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ck.png', 'Oceania'),
    ('Costa Rica', 'CR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/cr.png', 'Americas'),
    ('Croatia', 'HR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/hr.png', 'Europe'),
    ('Cuba', 'CU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/cu.png', 'Americas'),
    ('Cyprus', 'CY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/cy.png', 'Asia'),
    ('Czech Republic', 'CZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/cz.png', 'Europe'),
    ('Denmark', 'DK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/dk.png', 'Europe'),
    ('Djibouti', 'DJ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/dj.png', 'Africa'),
    ('Dominica', 'DM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/dm.png', 'Americas'),
    ('Dominican Republic', 'DO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/do.png', 'Americas'),
    ('Ecuador', 'EC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ec.png', 'Americas'),
    ('Egypt', 'EG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/eg.png', 'Africa'),
    ('El Salvador', 'SV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/sv.png', 'Americas'),
    ('Equatorial Guinea', 'GQ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/gq.png', 'Africa'),
    ('Eritrea', 'ER', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/er.png', 'Africa'),
    ('Estonia', 'EE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ee.png', 'Europe'),
    ('Ethiopia', 'ET', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/et.png', 'Africa'),
    ('Falkland Islands (Malvinas' ,'FK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/fk.png', 'Americas'),
    ('Faroe Islands', 'FO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/fo.png', 'Europe'),
    ('Fiji', 'FJ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/fj.png', 'Oceania'),
    ('Finland', 'FI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/fi.png', 'Europe'),
    ('France', 'FR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/fr.png', 'Europe'),
    ('French Guiana', 'GF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/gf.png', 'Americas'),
    ('French Polynesia', 'PF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/pf.png', 'Oceania'),
    ('Gabon', 'GA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ga.png', 'Africa'),
    ('Gambia', 'GM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/gm.png', 'Africa'),
    ('Georgia', 'GE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ge.png', 'Asia'),
    ('Germany', 'DE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/de.png', 'Europe'),
    ('Ghana', 'GH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/gh.png', 'Africa'),
    ('Gibraltar', 'GI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/gi.png', 'Europe'),
    ('Greece', 'GR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/gr.png', 'Europe'),
    ('Greenland', 'GL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/gl.png', 'Americas'),
    ('Grenada', 'GD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/gd.png', 'Americas'),
    ('Guadeloupe', 'GP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/gp.png', 'Americas'),
    ('Guam', 'GU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/gu.png', 'Oceania'),
    ('Guatemala', 'GT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/gt.png', 'Americas'),
    ('Guinea', 'GN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/gn.png', 'Africa'),
    ('Guinea-Bissau', 'GW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/gw.png', 'Africa'),
    ('Guyana', 'GY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/gy.png', 'Americas'),
    ('Haiti', 'HT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ht.png', 'Americas'),
    ('Holy See (Vatican City State' ,'VA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/va.png', 'Europe'),
    ('Honduras', 'HN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/hn.png', 'Americas'),
    ('Hong Kong', 'HK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/hk.png', 'Asia'),
    ('Hungary', 'HU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/hu.png', 'Europe'),
    ('Iceland', 'IS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/is.png', 'Europe'),
    ('India', 'IN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/in.png', 'Asia'),
    ('Indonesia', 'ID', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/id.png', 'Asia'),
    ('Iraq', 'IQ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/iq.png', 'Asia'),
    ('Ireland', 'IE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ie.png', 'Europe'),
    ('Isle of Man', 'IM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/im.png', 'Europe'),
    ('Israel', 'IL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/il.png', 'Asia'),
    ('Italy', 'IT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/it.png', 'Europe'),
    ('Jamaica', 'JM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/jm.png', 'Americas'),
    ('Japan', 'JP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/jp.png', 'Asia'),
    ('Jordan', 'JO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/jo.png', 'Asia'),
    ('Kazakhstan', 'KZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/kz.png', 'Asia'),
    ('Kenya', 'KE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ke.png', 'Africa'),
    ('Kiribati', 'KI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ki.png', 'Oceania'),
    ('Kuwait', 'KW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/kw.png', 'Asia'),
    ('Kyrgyzstan', 'KG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/kg.png', 'Asia'),
    ('Lao Peoples Democratic Republic', 'LA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/la.png', 'Asia'),
    ('Latvia', 'LV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/lv.png', 'Europe'),
    ('Lebanon', 'LB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/lb.png', 'Asia'),
    ('Lesotho', 'LS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ls.png', 'Africa'),
    ('Liberia', 'LR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/lr.png', 'Africa'),
    ('Libya', 'LY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ly.png', 'Africa'),
    ('Liechtenstein', 'LI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/li.png', 'Europe'),
    ('Lithuania', 'LT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/lt.png', 'Europe'),
    ('Luxembourg', 'LU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/lu.png', 'Europe'),
    ('Macao', 'MO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/mo.png', 'Asia'),
    ('Madagascar', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/mg.png', 'Africa'),
    ('Malawi', 'MW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/mw.png', 'Africa'),
    ('Malaysia', 'MY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/my.png', 'Asia'),
    ('Maldives', 'MV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/mv.png', 'Asia'),
    ('Mali', 'ML', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ml.png', 'Africa'),
    ('Malta', 'MT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/mt.png', 'Europe'),
    ('Marshall Islands', 'MH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/mh.png', 'Oceania'),
    ('Martinique', 'MQ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/mq.png', 'Americas'),
    ('Mauritania', 'MR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/mr.png', 'Africa'),
    ('Mauritius', 'MU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/mu.png', 'Africa'),
    ('Mayotte', 'YT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/yt.png', 'Africa'),
    ('Mexico', 'MX', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/mx.png', 'Americas'),
    ('Monaco', 'MC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/mc.png', 'Europe'),
    ('Mongolia', 'MN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/mn.png', 'Asia'),
    ('Montenegro', 'ME', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/me.png', 'Europe'),
    ('Montserrat', 'MS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ms.png', 'Americas'),
    ('Morocco', 'MA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ma.png', 'Africa'),
    ('Mozambique', 'MZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/mz.png', 'Africa'),
    ('Myanmar', 'MM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/mm.png', 'Asia'),
    ('Namibia', 'NA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/na.png', 'Africa'),
    ('Nauru', 'NR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/nr.png', 'Oceania'),
    ('Nepal', 'NP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/np.png', 'Asia'),
    ('Netherlands', 'NL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/nl.png', 'Europe'),
    ('New Caledonia', 'NC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/nc.png', 'Oceania'),
    ('New Zealand', 'NZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/nz.png', 'Oceania'),
    ('Nicaragua', 'NI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ni.png', 'Americas'),
    ('Niger', 'NE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ne.png', 'Africa'),
    ('Nigeria', 'NG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ng.png', 'Africa'),
    ('Niue', 'NU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/nu.png', 'Oceania'),
    ('Northern Mariana Islands', 'MP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/mp.png', 'Oceania'),
    ('Norway', 'NO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/no.png', 'Europe'),
    ('Oman', 'OM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/om.png', 'Asia'),
    ('Pakistan', 'PK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/pk.png', 'Asia'),
    ('Palau', 'PW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/pw.png', 'Oceania'),
    ('Panama', 'PA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/pa.png', 'Americas'),
    ('Papua New Guinea', 'PG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/pg.png', 'Oceania'),
    ('Paraguay', 'PY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/py.png', 'Americas'),
    ('Peru', 'PE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/pe.png', 'Americas'),
    ('Philippines', 'PH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ph.png', 'Asia'),
    ('Poland', 'PL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/pl.png', 'Europe'),
    ('Portugal', 'PT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/pt.png', 'Europe'),
    ('Puerto Rico', 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/pr.png', 'Americas'),
    ('Qatar', 'QA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/qa.png', 'Asia'),
    ('Romania', 'RO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ro.png', 'Europe'),
    ('Russian Federation', 'RU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ru.png', 'Europe'),
    ('Rwanda', 'RW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/rw.png', 'Africa'),
    ('Saint Kitts and Nevis', 'KN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/kn.png', 'Americas'),
    ('Saint Lucia', 'LC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/lc.png', 'Americas'),
    ('Saint Pierre and Miquelon', 'PM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/pm.png', 'Americas'),
    ('Saint Vincent and the Grenadines', 'VC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/vc.png', 'Americas'),
    ('Samoa', 'WS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ws.png', 'Oceania'),
    ('San Marino', 'SM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/sm.png', 'Europe'),
    ('Sao Tome and Principe', 'ST', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/st.png', 'Africa'),
    ('Saudi Arabia', 'SA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/sa.png', 'Asia'),
    ('Senegal', 'SN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/sn.png', 'Africa'),
    ('Serbia', 'RS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/rs.png', 'Europe'),
    ('Seychelles', 'SC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/sc.png', 'Africa'),
    ('Sierra Leone', 'SL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/sl.png', 'Africa'),
    ('Singapore', 'SG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/sg.png', 'Asia'),
    ('Sint Maarten (Dutch part' ,'SX', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/sx.png', 'Americas'),
    ('Slovakia', 'SK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/sk.png', 'Europe'),
    ('Slovenia', 'SI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/si.png', 'Europe'),
    ('Solomon Islands', 'SB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/sb.png', 'Oceania'),
    ('Somalia', 'SO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/so.png', 'Africa'),
    ('South Africa', 'ZA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/za.png', 'Africa'),
    ('South Sudan', 'SS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ss.png', 'Africa'),
    ('Spain', 'ES', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/es.png', 'Europe'),
    ('Sri Lanka', 'LK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/lk.png', 'Asia'),
    ('Sudan', 'SD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/sd.png', 'Africa'),
    ('Suriname', 'SR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/sr.png', 'Americas'),
    ('Swaziland', 'SZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/sz.png', 'Africa'),
    ('Sweden', 'SE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/se.png', 'Europe'),
    ('Switzerland', 'CH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ch.png', 'Europe'),
    ('Syrian Arab Republic', 'SY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/sy.png', 'Asia'),
    ('Tajikistan', 'TJ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/tj.png', 'Asia'),
    ('Thailand', 'TH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/th.png', 'Asia'),
    ('Timor-Leste', 'TL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/tl.png', 'Asia'),
    ('Togo', 'TG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/tg.png', 'Africa'),
    ('Tokelau', 'TK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/tk.png', 'Oceania'),
    ('Tonga', 'TO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/to.png', 'Oceania'),
    ('Trinidad and Tobago', 'TT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/tt.png', 'Americas'),
    ('Tunisia', 'TN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/tn.png', 'Africa'),
    ('Turkey', 'TR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/tr.png', 'Asia'),
    ('Turkmenistan', 'TM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/tm.png', 'Asia'),
    ('Turks and Caicos Islands', 'TC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/tc.png', 'Americas'),
    ('Tuvalu', 'TV', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/tv.png', 'Oceania'),
    ('Uganda', 'UG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ug.png', 'Africa'),
    ('Ukraine', 'UA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ua.png', 'Europe'),
    ('United Arab Emirates', 'AE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ae.png', 'Asia'),
    ('United Kingdom', 'GB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/gb.png', 'Europe'),
    ('United States', 'US', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/us.png', 'Americas'),
    ('Uruguay', 'UY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/uy.png', 'Americas'),
    ('Uzbekistan', 'UZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/uz.png', 'Asia'),
    ('Vanuatu', 'VU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/vu.png', 'Oceania'),
    ('Viet Nam', 'VN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/vn.png', 'Asia'),
    ('Wallis and Futuna', 'WF', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/wf.png', 'Oceania'),
    ('Western Sahara', 'EH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/eh.png', 'Africa'),
    ('Yemen', 'YE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/ye.png', 'Asia'),
    ('Zambia', 'ZM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/zm.png', 'Africa'),
    ('Zimbabwe', 'ZW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://flagcdn.com/h240/zw.png', 'Africa');
